[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{authors}}"]

[dependencies]
mirui = { version = "{{mirui-version}}", git = "https://github.com/W-Mai/mirui", rev = "39ed01becace7be4b533d43d2e3e5581a8448351", features = ["sdl"] }

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
strip = true
