[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{authors}}"]

[lib]
crate-type = ["cdylib"]

[dependencies]
mirui = { version = "{{mirui-version}}", features = ["wgpu-android"] }
winit = { version = "0.30", features = ["android-native-activity"] }

[package.metadata.android]
package = "{{android-package}}"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.sdk]
min_sdk_version = 26
target_sdk_version = 35

[package.metadata.android.application]
label = "{{project-name}}"
